language: cpp
sudo: required

services:
- docker

compiler:
- clang
- gcc
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6

env:
  global:
  - secure: gH8arUTB1PXCFQ4wlmO6Li9OJz7e6lETkB7lFkE3nGUycxacNfwc00pcD9blx/As28wswoE78XY+g9w54lKz4H/77kgRlKMPwK/UDkYnpDf/w9HwEMV/r6i2E1HQRGqC8YIZA/W0i+ppm/bnNFTvvc6uU3eyJuJcIryRiySwdyKdknLcQY6u6rNsTwz0igFzZvkysiul0Silw93MiRpbktu3yHvbWMVhM9yis29qdy9wBHrWk/ISDXhtHDYxTcssjUneF7VmlNesZ1uE5gepHDRGeoM5B1O9deVUomYokoi2pOS2niurm2PpsZgZONgjNJyBDtsk5R1KXwrtOsSkUO2Js09OcLc03Nzs7qCPKCMPiSbWe3dJegdHHUHD+ibCqM/cztMKQgSxyR/1iuOkWRo8BKQFTaJoiV0wYdo8IHLOR/jIqOSJkfLp49f40lztrqrgC/wJCx0iZtkDyAc/KtyQMAR/BVNif2tswOK+dqBKk8cAL35hjhdoDXPPsDlXA1Fbeca1ffx96RvCgp1bYFt1laQgtNMDQ9xCOmCjUiqPYQxhWic2rZQsEECPLAvJkqlGVtui1EY4ytm8VrrBtPbKXSLzEeb/R6bx6ToMJvI5d9MoHZ2dgrJ/STnnqkK5cvR1MupEzNHJhCYV/MIPjx7RwSHSrFnq+ubjfVjmdXY=
  - secure: DhpBcE9Eh0LwZvl790VrukpEI0WiBZFugQlJRIYPs4Sgz59rqjaRoSGSUkou2UqqI5240UMhSCTx/dxAgPipzZsJOcyrzMu0uulyhCO6AMCzMfFp/RCqCHqJ3bTy9f+Q/tiLMuxXd4/s0z6Vb5M+LNY7b2qVK6yDbL6YDZHQ+lBv9XoVfVbn7/K6zLBrW4WjOpEb0NcBzNbv5GVpL1fajNmAA8W0Du2EUNlFWLb6LXDbrMKwoHrlVOmCf4Q1jCbacoHSc/aTj7onAwtxFOV4ZoMZ5VP9uTd2TPD48KXlOsuruRJ4d0nP8nmi4ww3RxL6PyaQxNWvHiYktCtKsrrmy11W9FOFnXNFl4KlrVuD2bW2AK8cJQ4XdhQKkbWTehy4nDvVwD0Gai5jVJ8qp0RPlyo/Riv1XZExIPGEx7OcLOaVidXTlr1lNKq7goK6PY4Dn8yhzNNMhY8Z5fVRg+n71tzdsX61yIL1Sx0bgXUtnJmdhL4tNOeaUCB0lG9KRnpDvkSjgDCefiSZTsotrVOwmthp10yyWX16bzKVA8ks25roA9syBanTdW7OK2HnVpzky/ZhxHWuiJY76+ZVqg1hfQvCtyMV05qdNUGRV2EeDAASu1Or5Pas6uiqzJif5clxkE0a7L1ePCfKXs8H8BqNNyU7FYZbmUoMQFJg4AlZd+s=
  - secure: GQa2/y1D78BROlbAMh+otR6rrNNSR78nJghVg+TcnGP4gRvqE6Wrunk28K8iwgLsOsemNqEiqeeU3SHzCOpewP1EFdxlJx1PzgG3PgvGzuCUgesf/YsoVcrVsqnhlxnJ2wA6GLLu1q3uF2/sx0XPiQNBYpajCBMiIpkdPPVGhud0CyIKAqtedoxWUxh2y+17CBa1PXfle0+7J7Cnf4v/V743sF9XPVet2SYvtZ3Jl2yJYEXJF4RDjKeExTKONM0ethtbFPm8b4gchrqZj4KKsq0nJdNZsOoPPIoDRIzbHYFaSkWWQf9kA3AUtt1bNoHOChy9FT6I7gML+oac8ohuTjW56gCJL2ZyHNfiPNC8EhUH9N1Q/V5o1cuuyFf6DwOWCCahkoQ//hjLg1sUbgBI5+/80sHrVVhHzkb+HScPHcVD1ypTMObjtzeqh2/Zgqs5+YNE10hHdOTMbYWJHKqrpnVvHfAVJhsYbW9iWIrMUzWnF8zh4665SAgdADw8zGnskyj6r1fg7Gsm59lAjOgLxHuxAjsd4RtkQm4q/FRdJkf3Kc/DOZlurCyDcwaZWbcknp9yKtCsn8Uv7yMrGJprEnEGwyqVFPjerkjzQDUkOsxeFt5XBfWkjxXlhL7NWuB77W1JMz8H0lEaNaJZZMmMkvpvuA2LyHWDz71hE3YtL6M=
  - COMMIT=${TRAVIS_COMMIT::8}

before_install:
- export CC=/usr/bin/gcc-6
- export CXX=/usr/bin/g++-6
- sudo apt-get install build-essential gfortran pkg-config liblapack-dev libblas-dev
- wget --tries=40 --retry-connrefused --waitretry=1 --no-check-certificate https://www.coin-or.org/download/source/Ipopt/Ipopt-3.12.12.tgz
- tar xvzf Ipopt-3.12.12.tgz
- cd Ipopt-3.12.12/
- cd ThirdParty/Mumps
- "./get.Mumps"
- cd ../..
- "./configure --prefix=/usr/local"
- make -j5
- sudo make install
- cd ../
- echo $LANG
- echo $LC_ALL
- cd ./ext_lib/xlnt-1.3.0
- mkdir build
- cd build
- cmake ..
- make -j5
- cd ../../../
- mkdir build && cd build && cmake ..
script:
- make -j5
- cd ..
- "./bin/odo"
- cd ..

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=hhijazi01/odo
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- docker build -f ./ODO/Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
