language: cpp
sudo: required
compiler:
- clang
- gcc
os:
- linux
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-7
   - g++-7
before_install:
- sudo apt-get install gfortran
- sudo apt-get install libgfortran4
- export CC=/usr/bin/gcc-7  
- export CXX=/usr/bin/g++-7
- echo $LANG
- echo $LC_ALL
- cd ./ext_lib/xlnt-1.3.0
- mkdir build
- cd build
- cmake ..
- make -j5
- cd ../../../
- mkdir build && cd build && cmake ..
script:
- make -j5
- ../bin/odo
