language: cpp
sudo: required
compiler:
- clang
- gcc
os:
- linux
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-6
   - g++-6
before_install:
- sudo apt-get install gfortran
- export CC=/usr/bin/gcc-6  
- export CXX=/usr/bin/g++-6
- echo $LANG
- echo $LC_ALL
- cd ./ext_lib/xlnt-1.3.0
- mkdir build
- cd build
- cmake ..
- make -j5
- cd ../../../
- mkdir build && cd build && cmake ..
script:
- make -j5
- ../bin/odo
