language: cpp
sudo: required
compiler:
- clang
- gcc
os:
- linux
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-6
   - g++-6
before_install:
- export CC=/usr/bin/gcc-6
- export CXX=/usr/bin/g++-6
- sudo apt-get install build-essential gfortran pkg-config liblapack-dev libblas-dev
- wget https://www.coin-or.org/download/source/Ipopt/Ipopt-3.12.8.tgz
- tar xvzf Ipopt-3.12.8.tgz
- cd Ipopt-3.12.8/
- cd ThirdParty/Mumps
- ./get.Mumps
- cd ../..
- ./configure
- make -j5
- make install
- cd ../
- echo $LANG
- echo $LC_ALL
- cd ./ext_lib/xlnt-1.3.0
- mkdir build
- cd build
- cmake ..
- make -j5
- cd ../../../
- mkdir build && cd build && cmake ..
script:
- make -j5
- ../bin/odo
